/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package master_project;
package Security;

import Security.AES;
import java.awt.Color; 
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;



import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.text.PDFTextStripperByArea;

import java.awt.geom.Rectangle2D;
import java.io.File;
import java.io.IOException;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.text.PDFTextStripper;

import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import java.security.Key;
import java.util.Base64;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;


import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;








//import net.proteanit.sql.DbUtils;
/**
 *
 * @author Asus
 */
public class Pacienti extends javax.swing.JFrame {

    private String doctorNum;
    /**
     * Creates new form Pacienti
     */
    public Pacienti() {
        initComponents();
        decryptTableData();
        SelectPac();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    
     public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Buttonclose = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        Add_Pac = new javax.swing.JButton();
        Delete_Pac = new javax.swing.JButton();
        Mod_Pac = new javax.swing.JButton();
        Send_Mail = new javax.swing.JButton();
        Pac_Home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PacTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PacId = new javax.swing.JTextField();
        PacName = new javax.swing.JTextField();
        PacSurn = new javax.swing.JTextField();
        PacMail = new javax.swing.JTextField();
        PacCNP = new javax.swing.JTextField();
        PacDiag = new javax.swing.JTextField();
        PacRec = new javax.swing.JTextField();
        PacViz = new com.toedter.calendar.JDateChooser();
        PacProg = new com.toedter.calendar.JDateChooser();
        SearchBTN = new javax.swing.JButton();
        FMBtn = new javax.swing.JButton();
        StatsBtn = new javax.swing.JButton();
        ISBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Pacienti");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Aplicatie Medicala in Domeniul Psihiatriei");

        Buttonclose.setBackground(new java.awt.Color(0, 102, 102));
        Buttonclose.setLayout(new java.awt.BorderLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master_project/close icon.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(30, 35));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        Buttonclose.add(jLabel13, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Buttonclose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Buttonclose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });

        Add_Pac.setBackground(new java.awt.Color(0, 102, 102));
        Add_Pac.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Add_Pac.setForeground(new java.awt.Color(240, 240, 240));
        Add_Pac.setText("Adauga Pacient");
        Add_Pac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_PacMouseClicked(evt);
            }
        });

        Delete_Pac.setBackground(new java.awt.Color(0, 102, 102));
        Delete_Pac.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Delete_Pac.setForeground(new java.awt.Color(240, 240, 240));
        Delete_Pac.setText("Sterge Pacienti");
        Delete_Pac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_PacMouseClicked(evt);
            }
        });
        Delete_Pac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_PacActionPerformed(evt);
            }
        });

        Mod_Pac.setBackground(new java.awt.Color(0, 102, 102));
        Mod_Pac.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Mod_Pac.setForeground(new java.awt.Color(240, 240, 240));
        Mod_Pac.setText("Modifica Pacient");
        Mod_Pac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mod_PacMouseClicked(evt);
            }
        });

        Send_Mail.setBackground(new java.awt.Color(0, 102, 102));
        Send_Mail.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Send_Mail.setForeground(new java.awt.Color(240, 240, 240));
        Send_Mail.setText("Send Mail");
        Send_Mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Send_MailMouseClicked(evt);
            }
        });

        Pac_Home.setBackground(new java.awt.Color(0, 102, 102));
        Pac_Home.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Pac_Home.setForeground(new java.awt.Color(240, 240, 240));
        Pac_Home.setText("Home");
        Pac_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pac_HomeMouseClicked(evt);
            }
        });

        PacTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nume", "Prenume", "CNP", "Adresa Mail", "Diagnostic", "Reteta", "Data Vizita", "Data Programare"
            }
        ));
        PacTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        PacTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PacTable);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nr. Registru");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Nume");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Prenume");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("CNP");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Adresa Mail");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Diagnostic");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Reteta");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Data Vizita");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Data Programare");

        PacName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacNameActionPerformed(evt);
            }
        });

        PacSurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacSurnActionPerformed(evt);
            }
        });

        PacMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacMailActionPerformed(evt);
            }
        });

        PacCNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacCNPActionPerformed(evt);
            }
        });

        PacDiag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacDiagActionPerformed(evt);
            }
        });

        SearchBTN.setBackground(new java.awt.Color(0, 102, 102));
        SearchBTN.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SearchBTN.setForeground(new java.awt.Color(255, 255, 255));
        SearchBTN.setText("Find");
        SearchBTN.setActionCommand("");
        SearchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBTNMouseClicked(evt);
            }
        });

        FMBtn.setBackground(new java.awt.Color(0, 102, 102));
        FMBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        FMBtn.setForeground(new java.awt.Color(255, 255, 255));
        FMBtn.setText("Fisa Medicala");
        FMBtn.setPreferredSize(new java.awt.Dimension(91, 25));
        FMBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMBtnMouseClicked(evt);
            }
        });

        StatsBtn.setBackground(new java.awt.Color(0, 102, 102));
        StatsBtn.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        StatsBtn.setForeground(new java.awt.Color(255, 255, 255));
        StatsBtn.setText("Stats");
        StatsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatsBtnMouseClicked(evt);
            }
        });

        ISBTN.setBackground(new java.awt.Color(0, 102, 102));
        ISBTN.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ISBTN.setForeground(new java.awt.Color(255, 255, 255));
        ISBTN.setText("Istoric");
        ISBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ISBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Pac_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Send_Mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mod_Pac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Delete_Pac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Add_Pac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FMBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ISBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PacName)
                                    .addComponent(PacId)
                                    .addComponent(PacSurn, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(PacCNP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(PacDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PacRec)
                                                    .addComponent(PacViz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PacProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PacMail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StatsBtn)
                                .addGap(98, 98, 98)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(SearchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Add_Pac, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Delete_Pac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Mod_Pac, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Send_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FMBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ISBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pac_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PacDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PacId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PacName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PacRec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(PacSurn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PacViz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PacProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PacCNP, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PacMail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatsBtn)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void Delete_PacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_PacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_PacActionPerformed

    private void PacNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacNameActionPerformed

    private void PacSurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacSurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacSurnActionPerformed

    private void PacMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacMailActionPerformed

    private void PacCNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacCNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacCNPActionPerformed

    private void PacDiagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacDiagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacDiagActionPerformed

    public void SelectPac()
    {
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Licenta DB","andrei1","andrei1");
            St = Con.createStatement();
            Rs = St.executeQuery("select PACID as NR_REGISTRU, PACNAME as NUME, PACPREN as PRENUME, PACCNP as CNP, PACMAIL as MAIL, PACDIAG as DIAGNOSTIC, PACRECIO as RETETA, PACDATEVIS as DATA_VIZITA, PACDATEPROG as DATA_PROGRAMARE \n" +
"from PACIENTTBL p join USERTBL  u on (p.DOCTOR = u.UPHONE)\n" +
"where u.ONLINE = 1");
            PacTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e)
        {
            e.printStackTrace();
        }
    }
    
    public void encryptTableData() {
    try {
        Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Licenta DB", "andrei1", "andrei1");
        St = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

        
        Rs = St.executeQuery("select * from PACIENTTBL");

        while (Rs.next()) {
            int pacId = Rs.getInt("PACID");
            String name = AES.encrypt(Rs.getString("PACNAME"));
            String surname = AES.encrypt(Rs.getString("PACPREN"));
            int cnp = Rs.getInt("PACCNP");
            String mail = AES.encrypt(Rs.getString("PACMAIL"));
            String diag = AES.encrypt(Rs.getString("PACDIAG"));
            String rec = AES.encrypt(Rs.getString("PACRECIO"));

            
            Statement updateSt = Con.createStatement();

            String updateQuery = "update PACIENTTBL set PACNAME='" + name + "', PACPREN='" + surname + "', PACCNP=" + cnp + ", PACMAIL='" + mail + "', PACDIAG='" + diag + "', PACRECIO='" + rec + "' where PACID=" + pacId;
            updateSt.executeUpdate(updateQuery);

            
            updateSt.close();
        }

        St.close();
        Rs.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}



    
    
    public void decryptTableData() {
    try {
        Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Licenta DB", "andrei1", "andrei1");
        St = Con.createStatement();

        ResultSet rs = St.executeQuery("SELECT * FROM PACIENTTBL");

        while (rs.next()) {
            int id = rs.getInt("PACID");
            String name = AES.decrypt(rs.getString("PACNAME"));
            String surname = AES.decrypt(rs.getString("PACPREN"));
            int cnp = rs.getInt("PACCNP");
            String mail = AES.decrypt(rs.getString("PACMAIL"));
            String diag = AES.decrypt(rs.getString("PACDIAG"));
            String rec = AES.decrypt(rs.getString("PACRECIO"));
            Date dateVis = rs.getDate("PACDATEVIS");
            Date dateProg = rs.getDate("PACDATEPROG");

            String updateQuery = "UPDATE PACIENTTBL SET PACNAME='" + name + "', PACPREN='" + surname + "', PACCNP=" + cnp + ", PACMAIL='" + mail + "', PACDIAG='" + diag + "', PACRECIO='" + rec + "' WHERE PACID=" + id;
            Statement add = Con.createStatement();
            add.executeUpdate(updateQuery);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}


    
   java.util.Date PacVi, ReturnDat;
   java.sql.Date MyPacVi, MyReturnDat;
    
    private void Add_PacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_PacMouseClicked
         // TODO add your handling code here:
  
    try{
        PacVi = PacViz.getDate();
        MyPacVi = new java.sql.Date(PacVi.getTime());
        ReturnDat = PacProg.getDate();
        MyReturnDat = new java.sql.Date(ReturnDat.getTime());
        
        Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Licenta DB","andrei1","andrei1");

       
        String disorderCode = PacDiag.getText();
        PreparedStatement getDisorderName = Con.prepareStatement("SELECT NAME FROM MENTAL_DISORDERS WHERE CODE = ?");
        getDisorderName.setString(1, disorderCode);
        ResultSet rs = getDisorderName.executeQuery();
        String disorderName = "";
        if (rs.next()) {
            disorderName = rs.getString("NAME");
        }

        PreparedStatement add = Con.prepareStatement(
                "insert into PACIENTTBL values(?,?,?,?,?,?,?,?,?,(select UPHONE from USERTBL where ONLINE = 1))"
        );
        add.setInt(1, Integer.valueOf(PacId.getText()));
        add.setString(2, PacName.getText());
        add.setString(3, PacSurn.getText());
        add.setInt(4, Integer.valueOf(PacCNP.getText()));
        add.setString(5, PacMail.getText());
        add.setString(6, disorderName); 
        add.setString(7, PacRec.getText());
        add.setDate(8, MyPacVi);
        add.setDate(9, MyReturnDat);

        int row = add.executeUpdate();
        JOptionPane.showMessageDialog(this, "Pacientul a fost adaugat cu succes!");
        Con.close();
        SelectPac();
    }catch(SQLException e)
    {
        e.printStackTrace();
    }
    }//GEN-LAST:event_Add_PacMouseClicked

    private void Delete_PacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_PacMouseClicked
        // TODO add your handling code here:
        if(PacId.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Introduceti Pacientul pentru a putea fi sters");
        }
        else
        {
            try{
    Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Licenta DB","andrei1","andrei1");  
    String Id = PacId.getText();
    String Query = "Delete from andrei1.PACIENTTBL where PACID="+Id;
    Statement Add = Con.createStatement();
    Add.executeUpdate(Query);
    SelectPac();
    JOptionPane.showMessageDialog(this, "Pacientul a fost sters cu succes");
            }catch(SQLException e)
            {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_Delete_PacMouseClicked

    private void Pac_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pac_HomeMouseClicked
        encryptTableData();
        new MenuR().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Pac_HomeMouseClicked

    private void PacTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PacTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)PacTable.getModel();
        int Myindex = PacTable.getSelectedRow();
        PacId.setText(model.getValueAt (Myindex, 0).toString());
        PacName.setText(model.getValueAt (Myindex, 1).toString());
        PacSurn.setText(model.getValueAt (Myindex, 2).toString());
        PacCNP.setText(model.getValueAt (Myindex, 3).toString());
        PacMail.setText(model.getValueAt (Myindex, 4).toString());
        PacDiag.setText(model.getValueAt (Myindex, 5).toString());
        PacRec.setText(model.getValueAt (Myindex, 6).toString());
        Date dateValue = (Date) model.getValueAt(Myindex, 7);
        PacViz.setDate(dateValue);
        Date dateVal = (Date) model.getValueAt(Myindex, 8);
        PacProg.setDate(dateVal);
    }//GEN-LAST:event_PacTableMouseClicked

    private void Mod_PacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mod_PacMouseClicked
       if (PacId.getText().isEmpty() || PacName.getText().isEmpty() || PacSurn.getText().isEmpty() || PacCNP.getText().isEmpty() || PacMail.getText().isEmpty() || PacDiag.getText().isEmpty() || PacRec.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Lipsesc informatii despre pacient");
} else {
    try {
        Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Licenta DB","andrei1","andrei1");

       
        String disorderCode = PacDiag.getText();
        PreparedStatement getDisorderName = Con.prepareStatement("SELECT NAME FROM MENTAL_DISORDERS WHERE CODE = ?");
        getDisorderName.setString(1, disorderCode);
        ResultSet rs = getDisorderName.executeQuery();
        String disorderName = "";
        if (rs.next()) {
            disorderName = rs.getString("NAME");
        }

        String UpdateQuery = "UPDATE andrei1.PACIENTTBL SET PACNAME='" + PacName.getText() + "', PACPREN='" + PacSurn.getText() + "', PACCNP=" + PacCNP.getText() + ", PACMAIL='" + PacMail.getText() + "', PACDIAG='" + disorderName + "', PACRECIO='" + PacRec.getText() + "' WHERE PACID =" + PacId.getText();
        Statement Add = Con.createStatement();
        Add.executeUpdate(UpdateQuery);
        JOptionPane.showMessageDialog(this, "Pacient modificat cu succes!");
        SelectPac();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    }//GEN-LAST:event_Mod_PacMouseClicked

    private void Send_MailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Send_MailMouseClicked
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date selectedDate = PacProg.getDate();
        String dateString = dateFormat.format(selectedDate);
        
        String ToEmail = PacMail.getText();
        String FromEmail = "aplicatie.medicala41@gmail.com";
        String FromEmailPassword ="bhvdxfwqphnewcsi" ;
        String Subjects = "Programare Medicala";
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        properties.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
        
        Session session = Session.getDefaultInstance(properties,new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(FromEmail, FromEmailPassword);
            }
        });
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(FromEmail));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
            message.setSubject(Subjects);
            message.setText("Pacientul programat pe data: " + dateString);
            Transport.send(message);
        }catch(Exception ex){
                    System.out.println(""+ex);
                    }

    }//GEN-LAST:event_Send_MailMouseClicked

    private void SearchBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBTNMouseClicked
        String cautare;
        cautare = SearchBar.getText();
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Licenta DB","andrei1","andrei1");
            St = Con.createStatement();
            Rs = St.executeQuery("select PACNAME, PACPREN, PACCNP, PACMAIL, PACDIAG, PACRECIO, PACDATEVIS, PACDATEPROG \n" +
"from PACIENTTBL p join USERTBL  u on (p.DOCTOR = u.UPHONE)\n" + "where u.ONLINE = 1 AND LOWER(PACNAME) LIKE LOWER('%"+cautare+"%')" );
            PacTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e)
        {
            e.printStackTrace();
        }
        if (SearchBar.getText().isEmpty())
        {
            SelectPac();
        }
    }//GEN-LAST:event_SearchBTNMouseClicked

 
public void replaceTextInWord(String srcPath, String destPath) {
    try {
        FileInputStream fis = new FileInputStream(srcPath);
        XWPFDocument document = new XWPFDocument(fis);
        
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy"); 
        String pacVizString = formatter.format(PacViz.getDate());

        for (XWPFParagraph p : document.getParagraphs()) {
            List<XWPFRun> runs = p.getRuns();
            if (runs != null) {
                for (XWPFRun r : runs) {
                    String text = r.getText(0);
                    if (text != null) {
                        if (text.contains("PacName")) {
                            text = text.replace("PacName", PacName.getText());
                            r.setText(text, 0);
                        }
                        if (text.contains("PacSurn")) {
                            text = text.replace("PacSurn", PacSurn.getText());
                            r.setText(text, 0);
                        }
                        if (text.contains("PacCNP")) {
                            text = text.replace("PacCNP", PacCNP.getText());
                            r.setText(text, 0);
                        }
                        if (text.contains("PacViz")) {
                            text = text.replace("PacViz", pacVizString);
                            r.setText(text, 0);
                        }
                        if (text.contains("PacID")) {
                            text = text.replace("PacID", PacId.getText());
                            r.setText(text, 0);
                        }
                        if (text.contains("PacDiag")) {
                            text = text.replace("PacDiag", PacDiag.getText());
                            r.setText(text, 0);
                        }
                    }
                }
            }
        }
        fis.close();
        FileOutputStream out = new FileOutputStream(new File(destPath));
        document.write(out);
        out.close();
    } catch (IOException e) {
        e.printStackTrace();
    }
}


    
    private void FMBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMBtnMouseClicked
    
    Random rand = new Random();
    int randNum = rand.nextInt(10000) + 1;
    String filename = "C:/Users/Asus/Documents/NetBeansProjects/Master_Project_Test_6/src/SM/" + PacId.getText() + "_" + randNum + "_Scrisoare_Medicala.docx";
    
    replaceTextInWord("C:/Users/Asus/Documents/NetBeansProjects/Master_Project_Test_6/src/SM/Scrisoare_Medicala.docx", filename);

    }//GEN-LAST:event_FMBtnMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        encryptTableData();
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        changecolor(Buttonclose, new Color(25,29,74));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        changecolor(Buttonclose, new Color(0,102,102));
    }//GEN-LAST:event_jLabel13MouseExited

    private void StatsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatsBtnMouseClicked
      try {
    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Licenta DB","andrei1","andrei1");
    Statement stmt = con.createStatement();

    String query = "SELECT YEAR(PACIENTTBL.PACDATEVIS), MONTH(PACIENTTBL.PACDATEVIS), COUNT(PACIENTTBL.PACID) " +
        "FROM PACIENTTBL JOIN USERTBL ON PACIENTTBL.DOCTOR = USERTBL.UPHONE " +
        "WHERE USERTBL.ONLINE = 1 " +
        "GROUP BY YEAR(PACIENTTBL.PACDATEVIS), MONTH(PACIENTTBL.PACDATEVIS)";


    ResultSet rs = stmt.executeQuery(query);

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    while (rs.next()) {
        String yearMonth = rs.getInt(1) + "-" + String.format("%02d", rs.getInt(2));
        dataset.addValue(rs.getInt(3), "Pacienti", yearMonth);
    }

    JFreeChart chart = ChartFactory.createLineChart("Numarul de pacienti lunar",
            "Luna", "Numar", dataset, PlotOrientation.VERTICAL,
            true, true, false);
    
    NumberAxis yAxis = (NumberAxis) chart.getCategoryPlot().getRangeAxis();
    yAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

    ChartPanel chartPanel = new ChartPanel(chart);
    JFrame frame = new JFrame();
    frame.setContentPane(chartPanel);
    frame.pack();
    frame.setVisible(true);
} catch (SQLException throwables) {
    throwables.printStackTrace();
}

    }//GEN-LAST:event_StatsBtnMouseClicked

    private void ISBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ISBTNMouseClicked
        
     String directoryPath = "C:/Users/Asus/Documents/NetBeansProjects/Master_Project_Test_6/src/SM/";
    File directory = new File(directoryPath);
    File[] files = directory.listFiles((dir, name) -> name.startsWith(PacId.getText() + "_") && name.endsWith("_Scrisoare_Medicala.docx"));

    if (files.length > 0) {
        File chosenFile = (File) JOptionPane.showInputDialog(null, "Selectează fisa medicala pe care dorești să o deschizi:",
                "Deschide fisa medicala", JOptionPane.QUESTION_MESSAGE, null, files, files[0]);

        if (chosenFile != null) {
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(chosenFile);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("Deschiderea desktop-ului nu este suportata");
            }
        }
    } else {
        System.out.println("Fiaa medicala nu exista");
    }
    }//GEN-LAST:event_ISBTNMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacienti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pacienti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Pac;
    private javax.swing.JPanel Buttonclose;
    private javax.swing.JButton Delete_Pac;
    private javax.swing.JButton FMBtn;
    private javax.swing.JButton ISBTN;
    private javax.swing.JButton Mod_Pac;
    private javax.swing.JTextField PacCNP;
    private javax.swing.JTextField PacDiag;
    private javax.swing.JTextField PacId;
    private javax.swing.JTextField PacMail;
    private javax.swing.JTextField PacName;
    private com.toedter.calendar.JDateChooser PacProg;
    private javax.swing.JTextField PacRec;
    private javax.swing.JTextField PacSurn;
    private javax.swing.JTable PacTable;
    private com.toedter.calendar.JDateChooser PacViz;
    private javax.swing.JButton Pac_Home;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton Send_Mail;
    private javax.swing.JButton StatsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
